### ISSUE TITLE
Cada tarea gestionada por Alfred debería tener una firma

### ISSUE THREAD

**Issue by fmundaca** [Rankmi/alfred#52]
Sería bueno que cada tarea que gestiona Alfred en YT tenga una firma. Ya sea un campo extra o en la misma descripción

**Comment by rodrigonp** [comment]
#63 Al junto al url del Pull Request se agregará "*via **alfred***". Pensé en agregarle un tag, pero para proyectos como Desempeño se verían muy saturados.
