### ISSUE TITLE
Error al hacer un **alfred tasks **

### ISSUE THREAD

**Issue by fmundaca** [Rankmi/alfred#61]
![Captura de pantalla 2019-04-25 11 05 24](https://user-images.githubusercontent.com/340227/56746362-0e7fad00-674a-11e9-80e8-2e9a56878d3f.png)

**Comment by rodrigonp** [comment]
Esto pasa cuando no se encuentra la url base del API de Youtrack. Se hará un fix para setearla por defecto.
