### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by jesujcastillom** [Rankmi/alfred#66]
Yo tengo autenticación de 2 factores en GitHub, al ingresar mi usuario y clave de github (cosa que no debería hacer para el comando de `alfred update` dado que es un repo público) me aparece el siguiente error:

![image](https://user-images.githubusercontent.com/7827281/56903023-7cd5af80-6a69-11e9-85f7-99f844deffb2.png)

**Comment by rodrigonp** [comment]
El problema no es con 2FA, sino con que hay que definir el token de Github para realizar la acción. Como es un repo público, efectivamente no hay necesidad del token y voy a modificar la función para que no lo requiera.
¡Gracias por reportarlo!

**Comment by rodrigonp** [comment]
Se arreglará en #67
