### ISSUE TITLE
Alfred stops working if you udate it using sudo

### ISSUE THREAD

**Issue by efredz** [Rankmi/alfred#70]
~ ❯❯❯ alfred update
Github Username: efredzb@gmail.com
Github Password: 
Github Token: -
Downloading last binary realeased for Linux
mv: no se puede mover './alfred' a '/usr/local/bin/alfred': Permiso denegado
~ ❯❯❯ sudo !!
~ ❯❯❯ sudo alfred update
[sudo] contraseña para edgardo: 
Downloading last binary realeased for Linux
~ ❯❯❯ alfred -v
zsh: permiso denegado: alfred

**Comment by rodrigonp** [comment]
Old versions of alfred didn't automatically set permissions for the binary after updating. This is fixed with `sudo chmod +x /usr/local/bin/alfred`.
